name: Cleanup Cloudflare Worker Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: delete --env=${{ github.event.pull_request.number }}

      - name: Deactivate GitHub Deployments
        uses: actions/github-script@v6
        with:
          script: |
            const headSha = '${{ github.event.pull_request.head.sha }}';
            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: headSha
            });

            if (deployments.data.length > 0) {
              for (const deployment of deployments.data) {
                await github.rest.repos.createDeploymentStatus({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id,
                  state: 'inactive',
                  description: 'Preview deployment deleted'
                });
              }
            }
